// PET
export const GET_PETS = "GET_PETS";
export const GET_PET_BY_ID = "GET_PET_ID";
export const GET_PETS_BY_USER = "GET_PET_BY_USER";
export const GET_ADOPTION_PETS = "GET_ADOPTION_PETS_ADOPTION";
export const GET_LOST_PETS = "GET_LOST_PETS";
export const POST_PET = "POST_PET";
export const UPDATE_PET = "UPDATE_PET";
export const DELETE_PET = "DELETE_PET";

export const FILTER_ADOPTION_VALUES = "FILTER_ADOPTION_VALUES";
export const FILTER_BY_SEARCH_AREA = "FILTER_BY_SEARCH_AREA";

// TOKEN
export const CLEAR_TOKEN = "CLEAR_TOKEN";
export const SET_TOKEN = "SET_TOKEN";

// USER
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_USER_ID = "GET_USER_ID";
export const GET_CHECK_USERNAME = "GET_CHECK_USERNAME";
export const SET_USER = "SET_USER";
export const SET_STATUS_USER = "SET_STATUS_USER";
export const POST_USER = "POST_USER";
export const UPDATE_USER = "UPDATE_USER";

// VETERINARY
export const GET_VETERINARIES = "GET_VETERINARIES";
export const GET_DETAILS_VETERINARIES = "GET_DETAILS_VETERINARIES";
export const POST_VET = "POST_VET";
export const UPDATE_VET = "UPDATE_VET";

// PRODUCT 
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const POST_PRODUCT = "POST_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

// ECOMMERCE
export const SHOP_SEARCH_INPUT_NAME = "SHOP_SEARCH_INPUT_NAME";
export const SHOP_FILTER_VALUE = "SHOP_FILTER_VALUE";
export const MODIFY_PRODUCT = "MODIFY_PRODUCT";
export const OUT_OF_STOCK = "OUT_OF_STOCK";

// PAGE
export const NEXT_PAGE = "NEXT_PAGE";
export const PREV_PAGE = "PREV_PAGE";
export const ACTUAL_PAGE = "ACTUAL_PAGE";

// IMAGE
export const SET_IMAGE = "SET_IMAGE";
